- name: Disable Ipv6
  hosts: all
  become: true
  tasks:
   - name: Using Command sysctl -a | grep "disable_ipv6 = 0"
     shell: sysctl -a | grep "disable_ipv6 = 0"
     register: ipv6_parameters_before
     ignore_errors: true

   - name: Debugging
     debug:
       var: ipv6_parameters_before

   - name: Insert Lines into /etc/sysctl.conf and Apply Changes
     block: 
        - name: Insert Lines into sysctl.conf
          lineinfile:
            path: /etc/sysctl.conf
            line: "{{item | replace(' ','') | replace ('=0','=1') }}"
          loop: "{{ipv6_parameters_before.stdout_lines}}"

        - name: Apply Changes
          shell: sysctl -p
          register: ipv6_parameters_after

        - name: Debugging
          debug:
            var: ipv6_parameters_after

     when: ipv6_parameters_before.stdout_lines | length > 0
     ignore_errors: true

- name: Creating Report .CSV
  hosts: localhost
  tasks:
   - name: Using Template with Jinja 2
     template:
       src: ./report.template.j2
       dest: ./report.csv
